[package]
name = "journal_platform"
version = "1.0.0"
authors = []

[addresses]
journal_platform = "0xdf8185c47fe1be6c3bfceb8185da88769cfca09fc308cab61caa0a8b749c42b7"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
